import type { DocumentNode } from 'graphql'
export const typeDefs = {
  kind: 'Document',
  definitions: [
    {
      kind: 'ObjectTypeDefinition',
      name: { kind: 'Name', value: 'Query', loc: { start: 5, end: 10 } },
      interfaces: [],
      directives: [],
      fields: [],
      loc: { start: 0, end: 10 },
    },
    {
      kind: 'ObjectTypeDefinition',
      name: { kind: 'Name', value: 'Mutation', loc: { start: 17, end: 25 } },
      interfaces: [],
      directives: [],
      fields: [],
      loc: { start: 12, end: 25 },
    },
    {
      kind: 'ScalarTypeDefinition',
      name: { kind: 'Name', value: 'Date', loc: { start: 34, end: 38 } },
      directives: [],
      loc: { start: 27, end: 38 },
    },
    {
      kind: 'InputObjectTypeDefinition',
      name: { kind: 'Name', value: 'CreateFormData', loc: { start: 45, end: 59 } },
      directives: [],
      fields: [
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'name', loc: { start: 64, end: 68 } },
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 70, end: 76 } },
              loc: { start: 70, end: 76 },
            },
            loc: { start: 70, end: 77 },
          },
          directives: [],
          loc: { start: 64, end: 77 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'slug', loc: { start: 80, end: 84 } },
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 86, end: 92 } },
              loc: { start: 86, end: 92 },
            },
            loc: { start: 86, end: 93 },
          },
          directives: [],
          loc: { start: 80, end: 93 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'projectId', loc: { start: 96, end: 105 } },
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 107, end: 113 } },
              loc: { start: 107, end: 113 },
            },
            loc: { start: 107, end: 114 },
          },
          directives: [],
          loc: { start: 96, end: 114 },
        },
      ],
      loc: { start: 39, end: 116 },
    },
    {
      kind: 'InputObjectTypeDefinition',
      name: { kind: 'Name', value: 'UpdateFormInput', loc: { start: 124, end: 139 } },
      directives: [],
      fields: [
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'id', loc: { start: 144, end: 146 } },
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'ID', loc: { start: 148, end: 150 } },
              loc: { start: 148, end: 150 },
            },
            loc: { start: 148, end: 151 },
          },
          directives: [],
          loc: { start: 144, end: 151 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'name', loc: { start: 154, end: 158 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 160, end: 166 } },
            loc: { start: 160, end: 166 },
          },
          directives: [],
          loc: { start: 154, end: 166 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'introTitle', loc: { start: 169, end: 179 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 181, end: 187 } },
            loc: { start: 181, end: 187 },
          },
          directives: [],
          loc: { start: 169, end: 187 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'introMessage', loc: { start: 190, end: 202 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 204, end: 210 } },
            loc: { start: 204, end: 210 },
          },
          directives: [],
          loc: { start: 190, end: 210 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'promptTitle', loc: { start: 213, end: 224 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 226, end: 232 } },
            loc: { start: 226, end: 232 },
          },
          directives: [],
          loc: { start: 213, end: 232 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'promptDescription', loc: { start: 235, end: 252 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 254, end: 260 } },
            loc: { start: 254, end: 260 },
          },
          directives: [],
          loc: { start: 235, end: 260 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'thankyouTitle', loc: { start: 263, end: 276 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 278, end: 284 } },
            loc: { start: 278, end: 284 },
          },
          directives: [],
          loc: { start: 263, end: 284 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'thankyouMessage', loc: { start: 287, end: 302 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 304, end: 310 } },
            loc: { start: 304, end: 310 },
          },
          directives: [],
          loc: { start: 287, end: 310 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'enableCTA', loc: { start: 313, end: 322 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Boolean', loc: { start: 324, end: 331 } },
            loc: { start: 324, end: 331 },
          },
          directives: [],
          loc: { start: 313, end: 331 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'ctaTitle', loc: { start: 334, end: 342 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 344, end: 350 } },
            loc: { start: 344, end: 350 },
          },
          directives: [],
          loc: { start: 334, end: 350 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'ctaURL', loc: { start: 353, end: 359 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 361, end: 367 } },
            loc: { start: 361, end: 367 },
          },
          directives: [],
          loc: { start: 353, end: 367 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'isActive', loc: { start: 370, end: 378 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Boolean', loc: { start: 380, end: 387 } },
            loc: { start: 380, end: 387 },
          },
          directives: [],
          loc: { start: 370, end: 387 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'primaryColor', loc: { start: 390, end: 402 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 404, end: 410 } },
            loc: { start: 404, end: 410 },
          },
          directives: [],
          loc: { start: 390, end: 410 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'backgroundColor', loc: { start: 413, end: 428 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 430, end: 436 } },
            loc: { start: 430, end: 436 },
          },
          directives: [],
          loc: { start: 413, end: 436 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'lang', loc: { start: 439, end: 443 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 445, end: 451 } },
            loc: { start: 445, end: 451 },
          },
          directives: [],
          loc: { start: 439, end: 451 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'collectVideoTestimonials', loc: { start: 454, end: 478 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Boolean', loc: { start: 480, end: 487 } },
            loc: { start: 480, end: 487 },
          },
          directives: [],
          loc: { start: 454, end: 487 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'collectTextTestimonials', loc: { start: 490, end: 513 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Boolean', loc: { start: 515, end: 522 } },
            loc: { start: 515, end: 522 },
          },
          directives: [],
          loc: { start: 490, end: 522 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'collectRatings', loc: { start: 525, end: 539 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Boolean', loc: { start: 541, end: 548 } },
            loc: { start: 541, end: 548 },
          },
          directives: [],
          loc: { start: 525, end: 548 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'collectImages', loc: { start: 551, end: 564 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Boolean', loc: { start: 566, end: 573 } },
            loc: { start: 566, end: 573 },
          },
          directives: [],
          loc: { start: 551, end: 573 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'collectEmail', loc: { start: 576, end: 588 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Boolean', loc: { start: 590, end: 597 } },
            loc: { start: 590, end: 597 },
          },
          directives: [],
          loc: { start: 576, end: 597 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'collectJobTitle', loc: { start: 600, end: 615 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Boolean', loc: { start: 617, end: 624 } },
            loc: { start: 617, end: 624 },
          },
          directives: [],
          loc: { start: 600, end: 624 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'collectUserImage', loc: { start: 627, end: 643 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Boolean', loc: { start: 645, end: 652 } },
            loc: { start: 645, end: 652 },
          },
          directives: [],
          loc: { start: 627, end: 652 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'collectWebsiteURL', loc: { start: 655, end: 672 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Boolean', loc: { start: 674, end: 681 } },
            loc: { start: 674, end: 681 },
          },
          directives: [],
          loc: { start: 655, end: 681 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'collectCompany', loc: { start: 684, end: 698 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Boolean', loc: { start: 700, end: 707 } },
            loc: { start: 700, end: 707 },
          },
          directives: [],
          loc: { start: 684, end: 707 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'autoApproveTestimonials', loc: { start: 710, end: 733 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Boolean', loc: { start: 735, end: 742 } },
            loc: { start: 735, end: 742 },
          },
          directives: [],
          loc: { start: 710, end: 742 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'autoAddTags', loc: { start: 745, end: 756 } },
          type: {
            kind: 'ListType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 759, end: 765 } },
              loc: { start: 759, end: 765 },
            },
            loc: { start: 758, end: 766 },
          },
          directives: [],
          loc: { start: 745, end: 766 },
        },
      ],
      loc: { start: 118, end: 768 },
    },
    {
      kind: 'InputObjectTypeDefinition',
      name: { kind: 'Name', value: 'GetFormsInput', loc: { start: 776, end: 789 } },
      directives: [],
      fields: [
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'projectId', loc: { start: 794, end: 803 } },
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'ID', loc: { start: 805, end: 807 } },
              loc: { start: 805, end: 807 },
            },
            loc: { start: 805, end: 808 },
          },
          directives: [],
          loc: { start: 794, end: 808 },
        },
      ],
      loc: { start: 770, end: 810 },
    },
    {
      kind: 'ObjectTypeDefinition',
      name: { kind: 'Name', value: 'Form', loc: { start: 817, end: 821 } },
      interfaces: [],
      directives: [],
      fields: [
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'id', loc: { start: 826, end: 828 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'ID', loc: { start: 830, end: 832 } },
              loc: { start: 830, end: 832 },
            },
            loc: { start: 830, end: 833 },
          },
          directives: [],
          loc: { start: 826, end: 833 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'name', loc: { start: 836, end: 840 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 842, end: 848 } },
              loc: { start: 842, end: 848 },
            },
            loc: { start: 842, end: 849 },
          },
          directives: [],
          loc: { start: 836, end: 849 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'slug', loc: { start: 852, end: 856 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 858, end: 864 } },
              loc: { start: 858, end: 864 },
            },
            loc: { start: 858, end: 865 },
          },
          directives: [],
          loc: { start: 852, end: 865 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'introTitle', loc: { start: 868, end: 878 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 880, end: 886 } },
              loc: { start: 880, end: 886 },
            },
            loc: { start: 880, end: 887 },
          },
          directives: [],
          loc: { start: 868, end: 887 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'introMessage', loc: { start: 890, end: 902 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 904, end: 910 } },
            loc: { start: 904, end: 910 },
          },
          directives: [],
          loc: { start: 890, end: 910 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'promptTitle', loc: { start: 913, end: 924 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 926, end: 932 } },
              loc: { start: 926, end: 932 },
            },
            loc: { start: 926, end: 933 },
          },
          directives: [],
          loc: { start: 913, end: 933 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'promptDescription', loc: { start: 936, end: 953 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 955, end: 961 } },
            loc: { start: 955, end: 961 },
          },
          directives: [],
          loc: { start: 936, end: 961 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'thankyouTitle', loc: { start: 964, end: 977 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 979, end: 985 } },
              loc: { start: 979, end: 985 },
            },
            loc: { start: 979, end: 986 },
          },
          directives: [],
          loc: { start: 964, end: 986 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'thankyouMessage', loc: { start: 989, end: 1004 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 1006, end: 1012 } },
            loc: { start: 1006, end: 1012 },
          },
          directives: [],
          loc: { start: 989, end: 1012 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'enableCTA', loc: { start: 1015, end: 1024 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'Boolean', loc: { start: 1026, end: 1033 } },
              loc: { start: 1026, end: 1033 },
            },
            loc: { start: 1026, end: 1034 },
          },
          directives: [],
          loc: { start: 1015, end: 1034 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'ctaTitle', loc: { start: 1037, end: 1045 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 1047, end: 1053 } },
            loc: { start: 1047, end: 1053 },
          },
          directives: [],
          loc: { start: 1037, end: 1053 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'ctaURL', loc: { start: 1056, end: 1062 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 1064, end: 1070 } },
            loc: { start: 1064, end: 1070 },
          },
          directives: [],
          loc: { start: 1056, end: 1070 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'project', loc: { start: 1073, end: 1080 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Project', loc: { start: 1082, end: 1089 } },
            loc: { start: 1082, end: 1089 },
          },
          directives: [],
          loc: { start: 1073, end: 1089 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'projectId', loc: { start: 1092, end: 1101 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 1103, end: 1109 } },
              loc: { start: 1103, end: 1109 },
            },
            loc: { start: 1103, end: 1110 },
          },
          directives: [],
          loc: { start: 1092, end: 1110 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'createdBy', loc: { start: 1113, end: 1122 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'User', loc: { start: 1124, end: 1128 } },
            loc: { start: 1124, end: 1128 },
          },
          directives: [],
          loc: { start: 1113, end: 1128 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'createdByUserId', loc: { start: 1131, end: 1146 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 1148, end: 1154 } },
            loc: { start: 1148, end: 1154 },
          },
          directives: [],
          loc: { start: 1131, end: 1154 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'isActive', loc: { start: 1157, end: 1165 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'Boolean', loc: { start: 1167, end: 1174 } },
              loc: { start: 1167, end: 1174 },
            },
            loc: { start: 1167, end: 1175 },
          },
          directives: [],
          loc: { start: 1157, end: 1175 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'primaryColor', loc: { start: 1178, end: 1190 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 1192, end: 1198 } },
              loc: { start: 1192, end: 1198 },
            },
            loc: { start: 1192, end: 1199 },
          },
          directives: [],
          loc: { start: 1178, end: 1199 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'backgroundColor', loc: { start: 1202, end: 1217 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 1219, end: 1225 } },
              loc: { start: 1219, end: 1225 },
            },
            loc: { start: 1219, end: 1226 },
          },
          directives: [],
          loc: { start: 1202, end: 1226 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'lang', loc: { start: 1229, end: 1233 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 1235, end: 1241 } },
              loc: { start: 1235, end: 1241 },
            },
            loc: { start: 1235, end: 1242 },
          },
          directives: [],
          loc: { start: 1229, end: 1242 },
        },
        {
          kind: 'FieldDefinition',
          name: {
            kind: 'Name',
            value: 'collectVideoTestimonials',
            loc: { start: 1245, end: 1269 },
          },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'Boolean', loc: { start: 1271, end: 1278 } },
              loc: { start: 1271, end: 1278 },
            },
            loc: { start: 1271, end: 1279 },
          },
          directives: [],
          loc: { start: 1245, end: 1279 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'collectTextTestimonials', loc: { start: 1282, end: 1305 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'Boolean', loc: { start: 1307, end: 1314 } },
              loc: { start: 1307, end: 1314 },
            },
            loc: { start: 1307, end: 1315 },
          },
          directives: [],
          loc: { start: 1282, end: 1315 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'collectRatings', loc: { start: 1318, end: 1332 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'Boolean', loc: { start: 1334, end: 1341 } },
              loc: { start: 1334, end: 1341 },
            },
            loc: { start: 1334, end: 1342 },
          },
          directives: [],
          loc: { start: 1318, end: 1342 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'collectImages', loc: { start: 1345, end: 1358 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'Boolean', loc: { start: 1360, end: 1367 } },
              loc: { start: 1360, end: 1367 },
            },
            loc: { start: 1360, end: 1368 },
          },
          directives: [],
          loc: { start: 1345, end: 1368 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'collectEmail', loc: { start: 1371, end: 1383 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'Boolean', loc: { start: 1385, end: 1392 } },
              loc: { start: 1385, end: 1392 },
            },
            loc: { start: 1385, end: 1393 },
          },
          directives: [],
          loc: { start: 1371, end: 1393 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'collectJobTitle', loc: { start: 1396, end: 1411 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'Boolean', loc: { start: 1413, end: 1420 } },
              loc: { start: 1413, end: 1420 },
            },
            loc: { start: 1413, end: 1421 },
          },
          directives: [],
          loc: { start: 1396, end: 1421 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'collectUserImage', loc: { start: 1424, end: 1440 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'Boolean', loc: { start: 1442, end: 1449 } },
              loc: { start: 1442, end: 1449 },
            },
            loc: { start: 1442, end: 1450 },
          },
          directives: [],
          loc: { start: 1424, end: 1450 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'collectWebsiteURL', loc: { start: 1453, end: 1470 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'Boolean', loc: { start: 1472, end: 1479 } },
              loc: { start: 1472, end: 1479 },
            },
            loc: { start: 1472, end: 1480 },
          },
          directives: [],
          loc: { start: 1453, end: 1480 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'collectCompany', loc: { start: 1483, end: 1497 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'Boolean', loc: { start: 1499, end: 1506 } },
              loc: { start: 1499, end: 1506 },
            },
            loc: { start: 1499, end: 1507 },
          },
          directives: [],
          loc: { start: 1483, end: 1507 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'autoApproveTestimonials', loc: { start: 1510, end: 1533 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'Boolean', loc: { start: 1535, end: 1542 } },
              loc: { start: 1535, end: 1542 },
            },
            loc: { start: 1535, end: 1543 },
          },
          directives: [],
          loc: { start: 1510, end: 1543 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'autoAddTags', loc: { start: 1546, end: 1557 } },
          arguments: [],
          type: {
            kind: 'ListType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 1560, end: 1566 } },
              loc: { start: 1560, end: 1566 },
            },
            loc: { start: 1559, end: 1567 },
          },
          directives: [],
          loc: { start: 1546, end: 1567 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'createdAt', loc: { start: 1570, end: 1579 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Date', loc: { start: 1581, end: 1585 } },
            loc: { start: 1581, end: 1585 },
          },
          directives: [],
          loc: { start: 1570, end: 1585 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'updatedAt', loc: { start: 1588, end: 1597 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Date', loc: { start: 1599, end: 1603 } },
            loc: { start: 1599, end: 1603 },
          },
          directives: [],
          loc: { start: 1588, end: 1603 },
        },
      ],
      loc: { start: 812, end: 1605 },
    },
    {
      kind: 'ObjectTypeExtension',
      name: { kind: 'Name', value: 'Query', loc: { start: 1619, end: 1624 } },
      interfaces: [],
      directives: [],
      fields: [
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'getForms', loc: { start: 1629, end: 1637 } },
          arguments: [
            {
              kind: 'InputValueDefinition',
              name: { kind: 'Name', value: 'input', loc: { start: 1638, end: 1643 } },
              type: {
                kind: 'NonNullType',
                type: {
                  kind: 'NamedType',
                  name: { kind: 'Name', value: 'GetFormsInput', loc: { start: 1645, end: 1658 } },
                  loc: { start: 1645, end: 1658 },
                },
                loc: { start: 1645, end: 1659 },
              },
              directives: [],
              loc: { start: 1638, end: 1659 },
            },
          ],
          type: {
            kind: 'ListType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'Form', loc: { start: 1663, end: 1667 } },
              loc: { start: 1663, end: 1667 },
            },
            loc: { start: 1662, end: 1668 },
          },
          directives: [],
          loc: { start: 1629, end: 1668 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'getFormById', loc: { start: 1671, end: 1682 } },
          arguments: [
            {
              kind: 'InputValueDefinition',
              name: { kind: 'Name', value: 'id', loc: { start: 1683, end: 1685 } },
              type: {
                kind: 'NonNullType',
                type: {
                  kind: 'NamedType',
                  name: { kind: 'Name', value: 'ID', loc: { start: 1687, end: 1689 } },
                  loc: { start: 1687, end: 1689 },
                },
                loc: { start: 1687, end: 1690 },
              },
              directives: [],
              loc: { start: 1683, end: 1690 },
            },
          ],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Form', loc: { start: 1693, end: 1697 } },
            loc: { start: 1693, end: 1697 },
          },
          directives: [],
          loc: { start: 1671, end: 1697 },
        },
      ],
      loc: { start: 1607, end: 1699 },
    },
    {
      kind: 'ObjectTypeExtension',
      name: { kind: 'Name', value: 'Mutation', loc: { start: 1713, end: 1721 } },
      interfaces: [],
      directives: [],
      fields: [
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'createForm', loc: { start: 1726, end: 1736 } },
          arguments: [
            {
              kind: 'InputValueDefinition',
              name: { kind: 'Name', value: 'data', loc: { start: 1737, end: 1741 } },
              type: {
                kind: 'NonNullType',
                type: {
                  kind: 'NamedType',
                  name: { kind: 'Name', value: 'CreateFormData', loc: { start: 1743, end: 1757 } },
                  loc: { start: 1743, end: 1757 },
                },
                loc: { start: 1743, end: 1758 },
              },
              directives: [],
              loc: { start: 1737, end: 1758 },
            },
          ],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 1761, end: 1767 } },
            loc: { start: 1761, end: 1767 },
          },
          directives: [],
          loc: { start: 1726, end: 1767 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'updateForm', loc: { start: 1770, end: 1780 } },
          arguments: [
            {
              kind: 'InputValueDefinition',
              name: { kind: 'Name', value: 'data', loc: { start: 1781, end: 1785 } },
              type: {
                kind: 'NonNullType',
                type: {
                  kind: 'NamedType',
                  name: { kind: 'Name', value: 'UpdateFormInput', loc: { start: 1787, end: 1802 } },
                  loc: { start: 1787, end: 1802 },
                },
                loc: { start: 1787, end: 1803 },
              },
              directives: [],
              loc: { start: 1781, end: 1803 },
            },
          ],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Boolean', loc: { start: 1806, end: 1813 } },
            loc: { start: 1806, end: 1813 },
          },
          directives: [],
          loc: { start: 1770, end: 1813 },
        },
      ],
      loc: { start: 1701, end: 1815 },
    },
    {
      kind: 'InputObjectTypeDefinition',
      name: { kind: 'Name', value: 'CreateProjectData', loc: { start: 1822, end: 1839 } },
      directives: [],
      fields: [
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'name', loc: { start: 1844, end: 1848 } },
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 1850, end: 1856 } },
              loc: { start: 1850, end: 1856 },
            },
            loc: { start: 1850, end: 1857 },
          },
          directives: [],
          loc: { start: 1844, end: 1857 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'subdomain', loc: { start: 1860, end: 1869 } },
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 1871, end: 1877 } },
              loc: { start: 1871, end: 1877 },
            },
            loc: { start: 1871, end: 1878 },
          },
          directives: [],
          loc: { start: 1860, end: 1878 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'customDomain', loc: { start: 1881, end: 1893 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 1895, end: 1901 } },
            loc: { start: 1895, end: 1901 },
          },
          directives: [],
          loc: { start: 1881, end: 1901 },
        },
      ],
      loc: { start: 1816, end: 1903 },
    },
    {
      kind: 'ObjectTypeDefinition',
      name: { kind: 'Name', value: 'Project', loc: { start: 1910, end: 1917 } },
      interfaces: [],
      directives: [],
      fields: [
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'id', loc: { start: 1922, end: 1924 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'ID', loc: { start: 1926, end: 1928 } },
              loc: { start: 1926, end: 1928 },
            },
            loc: { start: 1926, end: 1929 },
          },
          directives: [],
          loc: { start: 1922, end: 1929 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'name', loc: { start: 1932, end: 1936 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 1938, end: 1944 } },
              loc: { start: 1938, end: 1944 },
            },
            loc: { start: 1938, end: 1945 },
          },
          directives: [],
          loc: { start: 1932, end: 1945 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'subdomain', loc: { start: 1948, end: 1957 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 1959, end: 1965 } },
              loc: { start: 1959, end: 1965 },
            },
            loc: { start: 1959, end: 1966 },
          },
          directives: [],
          loc: { start: 1948, end: 1966 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'customDomain', loc: { start: 1969, end: 1981 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 1983, end: 1989 } },
            loc: { start: 1983, end: 1989 },
          },
          directives: [],
          loc: { start: 1969, end: 1989 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'createdAt', loc: { start: 1992, end: 2001 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Date', loc: { start: 2003, end: 2007 } },
            loc: { start: 2003, end: 2007 },
          },
          directives: [],
          loc: { start: 1992, end: 2007 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'updatedAt', loc: { start: 2010, end: 2019 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Date', loc: { start: 2021, end: 2025 } },
            loc: { start: 2021, end: 2025 },
          },
          directives: [],
          loc: { start: 2010, end: 2025 },
        },
      ],
      loc: { start: 1905, end: 2027 },
    },
    {
      kind: 'ObjectTypeExtension',
      name: { kind: 'Name', value: 'Query', loc: { start: 2041, end: 2046 } },
      interfaces: [],
      directives: [],
      fields: [
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'getUserProjects', loc: { start: 2051, end: 2066 } },
          arguments: [],
          type: {
            kind: 'ListType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'Project', loc: { start: 2069, end: 2076 } },
              loc: { start: 2069, end: 2076 },
            },
            loc: { start: 2068, end: 2077 },
          },
          directives: [],
          loc: { start: 2051, end: 2077 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'getProjectByDomain', loc: { start: 2080, end: 2098 } },
          arguments: [
            {
              kind: 'InputValueDefinition',
              name: { kind: 'Name', value: 'domain', loc: { start: 2099, end: 2105 } },
              type: {
                kind: 'NonNullType',
                type: {
                  kind: 'NamedType',
                  name: { kind: 'Name', value: 'String', loc: { start: 2107, end: 2113 } },
                  loc: { start: 2107, end: 2113 },
                },
                loc: { start: 2107, end: 2114 },
              },
              directives: [],
              loc: { start: 2099, end: 2114 },
            },
          ],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Project', loc: { start: 2117, end: 2124 } },
            loc: { start: 2117, end: 2124 },
          },
          directives: [],
          loc: { start: 2080, end: 2124 },
        },
      ],
      loc: { start: 2029, end: 2126 },
    },
    {
      kind: 'ObjectTypeExtension',
      name: { kind: 'Name', value: 'Mutation', loc: { start: 2140, end: 2148 } },
      interfaces: [],
      directives: [],
      fields: [
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'createProject', loc: { start: 2153, end: 2166 } },
          arguments: [
            {
              kind: 'InputValueDefinition',
              name: { kind: 'Name', value: 'data', loc: { start: 2167, end: 2171 } },
              type: {
                kind: 'NonNullType',
                type: {
                  kind: 'NamedType',
                  name: {
                    kind: 'Name',
                    value: 'CreateProjectData',
                    loc: { start: 2173, end: 2190 },
                  },
                  loc: { start: 2173, end: 2190 },
                },
                loc: { start: 2173, end: 2191 },
              },
              directives: [],
              loc: { start: 2167, end: 2191 },
            },
          ],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Project', loc: { start: 2194, end: 2201 } },
            loc: { start: 2194, end: 2201 },
          },
          directives: [],
          loc: { start: 2153, end: 2201 },
        },
      ],
      loc: { start: 2128, end: 2203 },
    },
    {
      kind: 'InputObjectTypeDefinition',
      name: { kind: 'Name', value: 'CreateUserData', loc: { start: 2210, end: 2224 } },
      directives: [],
      fields: [
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'firstName', loc: { start: 2229, end: 2238 } },
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 2240, end: 2246 } },
              loc: { start: 2240, end: 2246 },
            },
            loc: { start: 2240, end: 2247 },
          },
          directives: [],
          loc: { start: 2229, end: 2247 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'lastName', loc: { start: 2250, end: 2258 } },
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 2260, end: 2266 } },
            loc: { start: 2260, end: 2266 },
          },
          directives: [],
          loc: { start: 2250, end: 2266 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'email', loc: { start: 2269, end: 2274 } },
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 2276, end: 2282 } },
              loc: { start: 2276, end: 2282 },
            },
            loc: { start: 2276, end: 2283 },
          },
          directives: [],
          loc: { start: 2269, end: 2283 },
        },
        {
          kind: 'InputValueDefinition',
          name: { kind: 'Name', value: 'password', loc: { start: 2286, end: 2294 } },
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 2296, end: 2302 } },
              loc: { start: 2296, end: 2302 },
            },
            loc: { start: 2296, end: 2303 },
          },
          directives: [],
          loc: { start: 2286, end: 2303 },
        },
      ],
      loc: { start: 2204, end: 2305 },
    },
    {
      kind: 'ObjectTypeDefinition',
      name: { kind: 'Name', value: 'User', loc: { start: 2312, end: 2316 } },
      interfaces: [],
      directives: [],
      fields: [
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'id', loc: { start: 2321, end: 2323 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'ID', loc: { start: 2325, end: 2327 } },
              loc: { start: 2325, end: 2327 },
            },
            loc: { start: 2325, end: 2328 },
          },
          directives: [],
          loc: { start: 2321, end: 2328 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'firstName', loc: { start: 2331, end: 2340 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 2342, end: 2348 } },
              loc: { start: 2342, end: 2348 },
            },
            loc: { start: 2342, end: 2349 },
          },
          directives: [],
          loc: { start: 2331, end: 2349 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'lastName', loc: { start: 2352, end: 2360 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 2362, end: 2368 } },
            loc: { start: 2362, end: 2368 },
          },
          directives: [],
          loc: { start: 2352, end: 2368 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'email', loc: { start: 2371, end: 2376 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'String', loc: { start: 2378, end: 2384 } },
              loc: { start: 2378, end: 2384 },
            },
            loc: { start: 2378, end: 2385 },
          },
          directives: [],
          loc: { start: 2371, end: 2385 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'emailVerified', loc: { start: 2388, end: 2401 } },
          arguments: [],
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'Boolean', loc: { start: 2403, end: 2410 } },
              loc: { start: 2403, end: 2410 },
            },
            loc: { start: 2403, end: 2411 },
          },
          directives: [],
          loc: { start: 2388, end: 2411 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'authenticationType', loc: { start: 2414, end: 2432 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 2434, end: 2440 } },
            loc: { start: 2434, end: 2440 },
          },
          directives: [],
          loc: { start: 2414, end: 2440 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'profileImageURL', loc: { start: 2443, end: 2458 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 2460, end: 2466 } },
            loc: { start: 2460, end: 2466 },
          },
          directives: [],
          loc: { start: 2443, end: 2466 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'role', loc: { start: 2469, end: 2473 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 2475, end: 2481 } },
            loc: { start: 2475, end: 2481 },
          },
          directives: [],
          loc: { start: 2469, end: 2481 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'createdAt', loc: { start: 2484, end: 2493 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Date', loc: { start: 2495, end: 2499 } },
            loc: { start: 2495, end: 2499 },
          },
          directives: [],
          loc: { start: 2484, end: 2499 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'updatedAt', loc: { start: 2502, end: 2511 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Date', loc: { start: 2513, end: 2517 } },
            loc: { start: 2513, end: 2517 },
          },
          directives: [],
          loc: { start: 2502, end: 2517 },
        },
      ],
      loc: { start: 2307, end: 2519 },
    },
    {
      kind: 'ObjectTypeExtension',
      name: { kind: 'Name', value: 'Query', loc: { start: 2533, end: 2538 } },
      interfaces: [],
      directives: [],
      fields: [
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'getSessionUser', loc: { start: 2543, end: 2557 } },
          arguments: [],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'User', loc: { start: 2559, end: 2563 } },
            loc: { start: 2559, end: 2563 },
          },
          directives: [],
          loc: { start: 2543, end: 2563 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'verifyGoogleAuthToken', loc: { start: 2566, end: 2587 } },
          arguments: [
            {
              kind: 'InputValueDefinition',
              name: { kind: 'Name', value: 'googleToken', loc: { start: 2588, end: 2599 } },
              type: {
                kind: 'NonNullType',
                type: {
                  kind: 'NamedType',
                  name: { kind: 'Name', value: 'String', loc: { start: 2601, end: 2607 } },
                  loc: { start: 2601, end: 2607 },
                },
                loc: { start: 2601, end: 2608 },
              },
              directives: [],
              loc: { start: 2588, end: 2608 },
            },
          ],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 2611, end: 2617 } },
            loc: { start: 2611, end: 2617 },
          },
          directives: [],
          loc: { start: 2566, end: 2617 },
        },
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'singinwithEmailPassword', loc: { start: 2620, end: 2643 } },
          arguments: [
            {
              kind: 'InputValueDefinition',
              name: { kind: 'Name', value: 'email', loc: { start: 2644, end: 2649 } },
              type: {
                kind: 'NonNullType',
                type: {
                  kind: 'NamedType',
                  name: { kind: 'Name', value: 'String', loc: { start: 2651, end: 2657 } },
                  loc: { start: 2651, end: 2657 },
                },
                loc: { start: 2651, end: 2658 },
              },
              directives: [],
              loc: { start: 2644, end: 2658 },
            },
            {
              kind: 'InputValueDefinition',
              name: { kind: 'Name', value: 'password', loc: { start: 2660, end: 2668 } },
              type: {
                kind: 'NamedType',
                name: { kind: 'Name', value: 'String', loc: { start: 2670, end: 2676 } },
                loc: { start: 2670, end: 2676 },
              },
              directives: [],
              loc: { start: 2660, end: 2676 },
            },
          ],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'String', loc: { start: 2679, end: 2685 } },
            loc: { start: 2679, end: 2685 },
          },
          directives: [],
          loc: { start: 2620, end: 2685 },
        },
      ],
      loc: { start: 2521, end: 2687 },
    },
    {
      kind: 'ObjectTypeExtension',
      name: { kind: 'Name', value: 'Mutation', loc: { start: 2701, end: 2709 } },
      interfaces: [],
      directives: [],
      fields: [
        {
          kind: 'FieldDefinition',
          name: { kind: 'Name', value: 'createUser', loc: { start: 2714, end: 2724 } },
          arguments: [
            {
              kind: 'InputValueDefinition',
              name: { kind: 'Name', value: 'data', loc: { start: 2725, end: 2729 } },
              type: {
                kind: 'NonNullType',
                type: {
                  kind: 'NamedType',
                  name: { kind: 'Name', value: 'CreateUserData', loc: { start: 2731, end: 2745 } },
                  loc: { start: 2731, end: 2745 },
                },
                loc: { start: 2731, end: 2746 },
              },
              directives: [],
              loc: { start: 2725, end: 2746 },
            },
          ],
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'User', loc: { start: 2749, end: 2753 } },
            loc: { start: 2749, end: 2753 },
          },
          directives: [],
          loc: { start: 2714, end: 2753 },
        },
      ],
      loc: { start: 2689, end: 2755 },
    },
  ],
  loc: { start: 0, end: 2756 },
} as unknown as DocumentNode
